# Adapted from <https://medium.com/@paweldudzinski/python-applications-continuous-integration-with-poetry-and-gitlab-pipelines-ac539888251a>

image: python:3.11

# Only run for merge requests or pushes to the default branch
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

before_script:
  - pip install poetry
  - poetry install

Check formatting:
  script:
    - poetry run black --check .

Check types:
  script:
    - poetry run mypy .

Check lints:
  script:
    - poetry run ruff .

Run unit tests:
  script:
    - poetry run pytest
