# Adapted from <https://medium.com/@paweldudzinski/python-applications-continuous-integration-with-poetry-and-gitlab-pipelines-ac539888251a>

image: python:3.11

# Only run for merge requests, not on every push
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - lint
  - test

before_script:
  - pip install poetry
  - poetry install

Check formatting:
  stage: lint
  script:
    - poetry run black --check .

Check types:
  stage: lint
  script:
    - poetry run pyright

Run unit tests:
  stage: test
  script:
    - poetry run pytest
