[tool.poetry]
name = "optimizer"
version = "0.1.0"
description = ""
authors = ["Tim Jentzsch <tim.jentzsch@rwth-aachen.de>"]

[tool.poetry.scripts]
start = "optimizer.main:main"

[tool.poetry.dependencies]
python = "^3.11"
PuLP = "^2.7.0"
pytest = "^7.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
