[tool.poetry]
name = "optimizer"
version = "0.1.0"
description = ""
authors = ["Tim Jentzsch <tim.jentzsch@rwth-aachen.de>"]

[tool.poetry.scripts]
start = "optimizer.main:main"

[tool.poetry.dependencies]
python = "^3.11"
PuLP = { git = "https://github.com/TimJentzsch/pulp.git", rev = "ff1f470320ecbe43afce48253e50b14cbc125757" }
pytest = "^7.2.0"
pyright = "^1.1.286"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
ruff = "^0.0.246"

[tool.pyright]
include = ["optimizer", "test"]
pythonVersion = "3.11"

[tool.ruff]
line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
