[tool.poetry]
name = "optimizer"
version = "0.1.0"
description = ""
authors = ["Tim Jentzsch <tim.jentzsch@rwth-aachen.de>"]

[tool.poetry.scripts]
start = "optimizer.main:main"

[tool.poetry.dependencies]
python = "^3.11"
PuLP = { git = "https://github.com/TimJentzsch/pulp.git", rev = "bbf66492535607c145add532a503160a3c00c330" }
pytest = "^7.2.0"
pyright = "^1.1.286"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"

[tool.pyright]
include = ["optimizer", "test"]
pythonVersion = "3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
